### ISSUE TITLE
Button zum Laden des Katalogs?

### ISSUE THREAD

**Issue by FloNio** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#1]
Soll ich nen Button zum Aktualisieren des Katalogs einbauen? Man soll die Aufgaben im Katalog ja sowieso außerhalb des Programms erstellen und bearbeiten. Dann würde ich vorschlagen, den Katalog im Katalog-Fenster updaten zu können anstatt das nur einmal am Anfang des Programms getan wird.

**Comment by asyndeton** [comment]
Sehr gute Idee.

**Comment by FloNio** [comment]
Dann müsst ich jetzt wissen, wie ist die Schnittstelle geregelt, implementiert Marvin ne Datenstruktur, die die Projekte einliest und in seiner Klasse als Objekte speichert? (Dann müsste ich ne Methode bekommen, die das Projekt bzw. die Aufgabe an der Stelle i [bei ner Liste] ausgibt, damit ich die TextArea mit den Einträgen dann via for-Schleife füllen kann) Oder erkläre mir einer kurz, wie das geplant ist (und ob wir uns bis Freitag überhaupt darum kümmern, oder erstma so grob bleiben, dass wir die Schnittstellen erstmal mit auskommentierung implementieren.

**Comment by garethbilaney** [comment]
Das sollten wir Freitag etwas genauer besprechen. vg Gareth

**Comment by asyndeton** [comment]
Das Laden des Katalogs kann mit CatalogueReader.readFromFile ausgelöst werden. Die Methode liefert eine Instanz der Klasse Catalogue, mit der man dann arbeiten kann. Siehe branch "catalogue".
