### ISSUE TITLE
Delete.java?

### ISSUE THREAD

**Issue by anjub100** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#12]
Hallo, ich habe die Delete.java-Datei im File-Interaction-Ordner gefunden. Dieser Code kann gar nicht funktionieren, weil das Klassennamen-System in meinen Opener- und Saver-Klassen anders funktioniert.
Wenn ihr dieser Klasse den Projekt- und Klassennamen übergeben könntet, könnte ich die Klasse so anpassen, dass sie die richtige Datei löscht. Allerdings würde ich aus der Klasse dann einen Datentypen machen, der wie die Opener- und Saver-Objekte funktioniert.

**Comment by garethbilaney** [comment]
Das können wir morgen gerne machen.

**Comment by barbieauglend** [comment]
Hallo =) Mach dann mal ;)

**Comment by garethbilaney** [comment]
@anjub100: Ich weiß nicht, ob das so passt. Eventuell solltest du die Klasse so anpassen, dass es für dich funktioniert.

**Comment by garethbilaney** [comment]
Bitte schaue auch nach, ob Saver und Opener hier korrekt aufgerufen werden:
https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe/blob/development/src/main/java/de/hhu/propra16/project7/controller/Logic.java

**Comment by anjub100** [comment]
@GaBil100 Ich hab's zwar noch nicht in Eclipse aufgerufen, aber auf den ersten Blick scheinen Saver und Opener richtig in die Klasse eingebunden zu sein. Ich werde mich jetzt erst einmal um Delete kümmern.
Meine Tracking-Klasse könnt ihr übrigens auch schon verwenden. Sie kann Compiler-Fehlermeldungen empfangen und formatiert ins Logfile schreiben. Die Fehlermeldungen kann man einfach von der toString-Methode aus der CompileError-Klasse erhalten.

**Comment by barbieauglend** [comment]
@anjub100 =) Es sieht sehr chic aus!

**Comment by anjub100** [comment]
@barbieauglend Danke! :)

Ich habe gerade die Opener- und Saver-Klassen verbessert und eine neue "Deleter"-Klasse erstellt. Diese Klasse bekommt einen Klassennamen und eine Statusvariable übergeben und löscht die entsprechende Datei im entsprechenden Ordner.
Diese Klasse ist natürlich als Ersatz für die alte "Delete"-Klasse gedacht, aber Delete.java enthält noch zwei zusätzliche Methoden "ReplaceCode" und "ReplaceTest", die meiner Meinung nach allerdings vollkommen sinnlos sind. Wenn diese Methoden tatsächlich nicht benötigt werden, kann die alte Delete-Klasse vollständig entfernt werden.

**Comment by barbieauglend** [comment]
@anjub100 Hey, André! Die Methoden werden aufgerufen, wenn man wieder die Vorlage haben möchte. Wir haben ja zwei Templates (schau bei Catalogue an) und die sollten dann geladen werden.

**Comment by anjub100** [comment]
@barbieauglend Ich habe die Methoden zwar gestern zum Deleter hinzugefügt, aber der Sinn erschließt sich mir immer noch nicht. Die Funktionen "Project.getInstructions" und "Project.getTestTemplates" geben doch lediglich einen String oder eine Liste zurück. Diese Objekte werden aber überhaupt nicht verarbeitet oder am Ende des Löschvorgangs von der open-Funktion zurückgeliefert, sind für das Programm also vollkommen nutzlos.

**Comment by barbieauglend** [comment]
@anjub100 jap - es kann sein, dass wir es wirklich nicht verwenden ... sorry!
