### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by garethbilaney** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#14]
Hallo @asyndeton , 

würdest du den Pfad der Catalogue-CFG-Datei die von deiner Klasse erstellt wird, schnell angeben?

Vg

Gareth

**Comment by asyndeton** [comment]
Moin,

CatalogueReader erstellt keine Konfigurationsdatei, sie lädt eine bestehende. Der Pfad ist nicht fest, sondern der Aufrufer von CatalogueReader.readFromFile übergibt eine File-Instanz (kann man schnell erzeugen per new File("...pfad...")). Sie kann also grundsätzlich überall liegen, der Aufruf entscheidet.

Grüße,

Marvin

**Comment by barbieauglend** [comment]
Hum.... Das ist, was wir gemacht haben =/

Ok. Danke =)

**Comment by asyndeton** [comment]
Kannst du (könnt ihr), kurz den Commit oder die Datei verlinken, wo ihr das versucht habt? Dann seh ich vielleicht das Problem.

**Comment by barbieauglend** [comment]
Da ist es =)
