### ISSUE TITLE
Morgen ??

### ISSUE THREAD

**Issue by barbieauglend** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#15]
Hallo @asyndeton ,

Hast Du morgen Zeit, um die Verbindung von Catalogue mit Controller und Logic zu besprechen?

Wir (Gareth, Florian und Thaís) hätten morgen Zeit.

@anjub100 Ich glaube, du brauchst nicht kommen =) Wenn Du Zeit hast, kannst Du trotzdem gern auch dabei sein.

LG
Thaís

**Comment by asyndeton** [comment]
Moin,

Joa, ich hätte morgen Zeit, möglichst 12:00 (hätt ich ne halbe Stunde) oder ab 14:00 (unbeschränkt).

Grüße,

Marvin

**Comment by barbieauglend** [comment]
Hey =)

Dann morgen 14 Uhr, wo denn?

LG
Thaís

**Comment by anjub100** [comment]
Hallo, ich werde morgen nicht kommen, weil meine Klassen ausschließlich Datentypen sind, die von euren Klassen aufgerufen werden (und nicht umgekehrt). Spätestens wenn ich meine Systembeschreibung geschrieben habe, sollte es eigentlich keine Fragen mehr geben. Falls doch, können wir alles über die Issues klären.
Trotzdem viel Erfolg beim Treffen morgen! ;)

**Comment by asyndeton** [comment]
Wie wärs mit 26.11? Das ist vor den Hörsälen 6A-D, da sind zig Sitzecken, irgendeine ist immer frei.

**Comment by barbieauglend** [comment]
Supi! Bis dann!

**Comment by barbieauglend** [comment]
Zug verpasst - können wir 10 nach machen? Sorry!

**Comment by asyndeton** [comment]
Klar!

**Comment by barbieauglend** [comment]
Danke! Bis gleich :)
