### ISSUE TITLE
Prokolle in Master

### ISSUE THREAD

**Issue by garethbilaney** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#19]
Da so langsam alles in Master zusammengefasst wird, viele Branches gelöscht wurden, könnten wir doch alle Prokolle auch hier verlagern:

https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe/tree/master/protokoll

**Comment by barbieauglend** [comment]
Ja, die, die wir nicht brauche weil schon gemerged wurden und nicht mehr bearbeitet werden sollen. Wir arbeiten eh in Development jetzt.
