### ISSUE TITLE
Treffen

### ISSUE THREAD

**Issue by garethbilaney** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#2]
Hättet ihr alle morgen, 12.15 Zeit? Also wie letzte Woche.

**Comment by asyndeton** [comment]
Jo.

**Comment by barbieauglend** [comment]
Ich bin leider noch nicht da.

**Comment by FloNio** [comment]
Werde da sein

**Comment by anjub100** [comment]
Ja. Es wäre aber gut, wenn es sich nicht so lange wie letzte Woche hinzieht. Ich will das Tutorium nur ungern zum zweiten Mal in Folge verpassen...
