### ISSUE TITLE
Letztes (?) Treffen

### ISSUE THREAD

**Issue by FloNio** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#20]
Können wir uns nochmal Treffen, um die letzten Sachen abzustimmen? Ich muss mit Gareth die Babysteps optimieren und mit Andre auf jeden Fall noch abstimmen, wie ich meine Radiobuttons einbauen kann, um Tracking (Ja/Nein) zu enablen. Bzw. wo wir das genau ansagen, dass Tracking gemacht werden soll.

Morgen bin ich beispielsweise mit Gareth ab 10 in der Uni. Wenn jemand (Andre vllt) Lust hat, einfach dazustoßen ;)

**Comment by barbieauglend** [comment]
Wann?

**Comment by garethbilaney** [comment]
Florian und ich werden aufjedenfall morgen, 10 Uhr da sein.

**Comment by anjub100** [comment]
@FloNio _"Ich muss [...] mit Andre auf jeden Fall noch abstimmen, wie ich meine Radiobuttons einbauen kann, um Tracking (Ja/Nein) zu enablen."_
Wie Tracking aufgerufen wird, ist eigentlich die Aufgabe der Logik-Klasse.

Ich hätte morgen erst ab ~14:15 Zeit. Würde aber gerne auch noch einmal über Babysteps reden, weil ich gerade mehrere Funktionen in meine Tracking-Klasse eingebaut habe, die mit Babysteps arbeiten.

**Comment by garethbilaney** [comment]
Wunderbar. Tracking kann ich morgen früh in der logik einbauen.

**Comment by barbieauglend** [comment]
Morgen schreibe ich ja eine schwierige Klausur. Ich bin heute leider raus. Morgen nach 16 Uhr wieder dabei =)
