### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by garethbilaney** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#23]
@anjub100 

Hi Andre,

den Tracker habe so eingebaut:
tracker.statusChanged(getStatus(), returnRunTime(), Minuten);

Hoffe, das ist so richtig. Bitte schaue Mal in der Logik nach, ob ich eventuell Fehler gemacht habe.

Eine Kleinigkeit:

Wie sieht es bei  „int maxtime“ aus, wenn BabySteps aus ist?

Ich habe dort einfach in Logic-java eine -1 eingegeben:

tracker.statusChanged(getStatus(), returnRunTime(), -1); 

Viele Grüße,

Gareth

**Comment by anjub100** [comment]
@GaBil100 Hallo, das scheint zu funktionieren. Die Methode, die Laufzeit durch getCurrentTimeMillis() zu erhalten, gefällt mir übrigens auch. ^^

Die maxtime kann irgendeinen Wert haben, wenn Babysteps nicht aktiviert ist, weil sie in diesem Fall gar nicht überprüft wird. Sie könnte z.B. auch null sein; das spielt für die Funktion gar keine Rolle.

**Comment by garethbilaney** [comment]
Das freut mich, zu hören. Da fällt mir gerade auf, dass ich die Differenz der Zeit nicht beachtet habe. Aber das ist eine Kleinigkeit.

**Comment by garethbilaney** [comment]
Tracking funktioniert wunderbar. Jetzt werden auch die Zeiten von Logic korrekt übergeben.

**Comment by anjub100** [comment]
Die Funktion "timesUp" müsste noch aufgerufen werden, wenn die Zeit von Babysteps abgelaufen ist und der Fortschritt des Nutzers zurückgesetzt wird. Ich hab versucht, die entsprechende Stelle in eurem Code zu finden, habe sie aber leider nicht ausfindig machen können.

**Comment by garethbilaney** [comment]
Ich setze mich gleich dran, sobald ich meine Lerneinheit durch habe.
