### ISSUE TITLE
Vorschlag: Enumerationstyp für die Phase

### ISSUE THREAD

**Issue by asyndeton** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#4]
Moin,

da ich grad die Definitionendatei sah, wollte ich nur mal kurz anregen, statt einem int einfach einen Enumerationstypen zu verwenden. Ungefähr so ginge das:

```
public static enum Phase {
    Red,
    Green,
    Refactor
} 
private Phase aktuellePhase = Phase.Red;
```

Dann kommen wir da auch nicht durcheinander und brauchen die Definitionendatei gar nicht mehr :)
Könnten wir ja morgen auch drüber sprechen.

**Comment by barbieauglend** [comment]
erledigt
