### ISSUE TITLE
Diese Woche 

### ISSUE THREAD

**Issue by barbieauglend** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#5]
Wann treffen wir uns dieser Woche? 

Wieder Freitag 12:15?

**Comment by garethbilaney** [comment]
yes

**Comment by anjub100** [comment]
Ja.

**Comment by barbieauglend** [comment]
Wollen wir in der Bib einen Raum buchen?

**Comment by garethbilaney** [comment]
Sehr gerne

**Comment by barbieauglend** [comment]
Dabei - brauche eine zweite Uni Kennung :) wer will?

**Comment by garethbilaney** [comment]
Braucht man einen Büchereiausweis? In dem Fall kann ich mich leider nicht anbieten.

**Comment by barbieauglend** [comment]
Nein :)

**Comment by garethbilaney** [comment]
Ok, dann ist meine Unikennung: gabil100

**Comment by barbieauglend** [comment]
Erledigt - bis morgen !
