### ISSUE TITLE
CompilationUnit und Logik-Architektur

### ISSUE THREAD

**Issue by garethbilaney** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#7]
_blub_

**Comment by barbieauglend** [comment]
@anjub100 Compilation Unit läuft bei mir. Der Fehler kommt erst bei Zeile 50 aber ich nehme an, es hat was mit dem Pfad zu tun.

**Comment by garethbilaney** [comment]
Das ist doch schon mal gut. 

Ich habe hier eine Klasse erstellt, an der wir arbeiten können. In dieser steht ganz grob die Funktionalität:

https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe/blob/Logik/Compile.java

Im Prinzip sollten Klassenname und Code eingelesen werden und ein boolean [kompiliert ja/nein?]  ausgegeben werden. 

Laut http://kata.bendisposto.de/ → CompilerResult sollte genau das mithilfe von **hasCompileErrors()**  geschehen.

**Comment by barbieauglend** [comment]
Jap - :) ich habe jetzt Development erzeugt , um die Mail klasse zu schreiben und das programm zu testen

**Comment by garethbilaney** [comment]
Habe dich jetzt gerade bei Skype angeschrieben.

**Comment by anjub100** [comment]
@barbieauglend Dann lag es wahrscheinlich doch nur an Eclipse... 
Weil ihr euch um die Logik kümmert, werde ich diese Codezeilen einfach komplett entfernen und mich wieder um meinen Teil kümmern.

**Comment by garethbilaney** [comment]
In Ordnung

**Comment by barbieauglend** [comment]
Erledigt!
