### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by semey102** [ProPra16/programmierpraktikum-abschlussprojekt-two-finger-joe#9]
Hallo zusammen,

ich bin euer Korrektor für das Gruppenprojekt. Ich würde mich gerne am Montag 12:10 oder 14:10 in 25.12.00.82 (Computerraum) kurz mit euch treffen. Das ganze wird ca. 10min dauern.

Könnt ihr mir bitte kurz bescheidgeben, ob der Termin für euch alle passt.

Gruß Sebastian

**Comment by garethbilaney** [comment]
Hallo Sebastian,
Ich habe von 12:30-14:00 eine Übung. Bei einem Gespräch von 10 Minuten müsste jedoch 12:10 bei mir gehen. Da mein Übungleiter gerne überzieht, wäre 14:10 etwas problematisch bei mir. 

Viele Grüße,

Gareth

**Comment by asyndeton** [comment]
Für mich sind beide Zeiten machbar.

**Comment by anjub100** [comment]
Für mich wären auch beide Termine möglich...

**Comment by barbieauglend** [comment]
12:10 kann ich auch!

**Comment by semey102** [comment]
Ok. Dann treffen wir uns am Montag 12:10 in 25.12.00.82 (Computerraum).

**Comment by anjub100** [comment]
Ist wirklich Raum 25.12.00.82 gemeint oder sollte es vielleicht 25.22.00.82 heißen? Das ist nämlich der Raum, in dem die Propra-Übungsgruppen stattfinden.

**Comment by semey102** [comment]
Dann meine ich wohl den. Also in dem raum, wo die Übungen stattfinden.
